trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Install Maven 3.9.0 manually
- script: |
    wget https://archive.apache.org/dist/maven/maven-3/3.9.0/binaries/apache-maven-3.9.0-bin.tar.gz
    tar -xvf apache-maven-3.9.0-bin.tar.gz
    sudo mv apache-maven-3.9.0 /opt/
    sudo ln -s /opt/apache-maven-3.9.0/bin/mvn /usr/local/bin/mvn
    mvn --version  # Confirm the Maven version
  displayName: 'Install Maven 3.9.0'

# Run Maven build with Maven 3.9.0 using the provided options
- script: |
    mvn clean package -Xmx3072m \
      -Dmaven.test.failure.ignore=false \
      -Dmaven.test.redirectTestOutputToFile=true \
      -DtestResultsFiles=**/surefire-reports/TEST-*.xml \
      -Dgoal=package \
      -DpomFile=pom.xml
  displayName: 'Run Maven Build'